config/routes.rb
Rails.application.routes.draw do
  get 'search/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :products, only: [:index, :show]
  resources :categories, only: [:index, :show]
  resources :users, only: [:index, :show]
  resources :reviews, only: [:index, :show]
  resources :orders, only: [:index, :show]
  resources :order_items, only: [:index, :show]
  resources :contacts, only: [:show]
  resources :abouts, only: [:show]
  resources :search, only: :index
  get 'search', to: 'search#index', as: 'search'
  resources :products do
    collection do
      get :index, defaults: { filter: 'All Products' }
    end
  end

end

app/models/active_storage_attachment/attachment.rb
class ActiveStorage::Attachment < ApplicationRecord
  def self.ransackable_attributes(auth_object = nil)
    ["blob_id", "created_at", "id", "name", "record_id", "record_type"]
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
   end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "order_id", "product_id", "quantity", "updated_at"]
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :order_items
  has_many :reviews
  has_one_attached :image

  def self.ransackable_attributes(auth_object = nil)
    ["category_id", "created_at", "description", "id", "name", "price", "updated_at"]
  end
  def self.ransackable_associations(auth_object = nil)
    ["category", "image_attachment", "image_blob", "order_items", "reviews"]
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :product

  def self.ransackable_attributes(auth_object = nil)
    ["content", "created_at", "id", "product_id", "updated_at", "user_id"]
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.page(params[:page]).per(10)
  end
  def show
    @category = Category.find(params[:id])
    @products = @category.products.page(params[:page]).per(10)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    case params[:filter]
    when "on_sale"
      @products = Product.where("price < ?", 100).page(params[:page]).per(10)
      @on_sale_products = @products
    when "new"
      @new_products = Product.where("created_at >= ?", 3.days.ago).page(params[:page]).per(10)
      @products = @new_products
    when "recently_updated"
      @new_products = Product.where("created_at >= ?", 3.days.ago).page(params[:page]).per(10)
      @recently_updated_products = Product.where("updated_at >= ?", 3.days.ago).page(params[:page]).per(10)
                                         .where.not(id: @new_products.pluck(:id))
      @products = @recently_updated_products
    else
      @products = Product.page(params[:page]).per(10)
    end

    @on_sale_products ||= Product.where("price < ?", 100).page(params[:page]).per(10)
  end

  def show
    @product = Product.find(params[:id])
  end

  private

  def calculate_sale_price(original_price)
    sale_percentage = 10
    sale_price = original_price - (original_price * sale_percentage / 100)
    sale_price
  end
end

app/controllers/search_controller.rb
# app/controllers/search_controller.rb

class SearchController < ApplicationController
  def index
    @categories = Category.all

    if params[:keyword].present?
      @products = Product.where("name LIKE ?", "%#{params[:keyword]}%")
    else
      @products = Product.all
    end

    if params[:category_id].present?
      @products = @products.where(category_id: params[:category_id])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/categories/index.html.erb
<h1>All Categories</h1>

<% if @categories.any? %>
  <ul>
    <% @categories.each do |category| %>
      <li><%= link_to category.name, category_path(category) %></li>
    <% end %>
  </ul>
<%= paginate @categories %>
<% else %>
  <p>No categories found.</p>
<% end %>

app/views/categories/show.html.erb
<h1><%= @category.name %> Category</h1>
<%= link_to "View Products", category_path(@category) %>

<!-- Other category details can be displayed here -->

<% if @products.any? %>
  <h2>Products in <%= @category.name %> Category</h2>
  <ul>
    <% @products.each do |product| %>
      <li><%= link_to product.name, product_path(product) %></li>
    <% end %>
  </ul>
  <%= paginate @products %>
<% else %>
  <p>No products found in <%= @category.name %> Category.</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BeautyGlamour</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <nav>
  <%= link_to "All Categories", categories_path %>
  <%= link_to "All Products", products_path %>
  <%= link_to "Search", search_path %>
  </nav>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<h1>Products</h1>

<p>Search and explore your favorite products here: <%= link_to "Search for products", search_path %></p>
<%= form_tag(products_path, method: "get") do %>
  <%= select_tag :filter, options_for_select({ "All Products" => "", "On Sale" => "on_sale", "New Products" => "new", "Recently Updated" => "recently_updated" }, params[:filter]) %>
  <%= submit_tag "Filter" %>
<% end %>

<% if params[:filter].blank? || params[:filter] == "All Products" %>
  <h2>All Products</h2>
  <% if @products.any? %>
    <ul>
      <% @products.each do |product| %>
        <li><%= link_to product.name, product_path(product) %></li>
        <!-- You can add additional information here if needed -->
      <% end %>
    </ul>
    <%= paginate @products %>
  <% else %>
    <p>No products found.</p>
  <% end %>

<% elsif params[:filter] == "on_sale" %>
  <h2>On Sale Products</h2>
  <% if @on_sale_products.any? %>
    <ul>
      <% @on_sale_products.each do |product| %>
        <li><%= link_to product.name, product_path(product) %></li>
        <!-- You can add additional information here if needed -->
      <% end %>
    </ul>
    <%= paginate @on_sale_products %>
  <% else %>
    <p>No on-sale products found.</p>
  <% end %>

<% elsif params[:filter] == "new" %>
  <h2>New Products</h2>
  <% if @new_products.any? %>
    <ul>
      <% @new_products.each do |product| %>
        <li><%= link_to product.name, product_path(product) %></li>
      <% end %>
    </ul>
    <%= paginate @new_products %>
  <% else %>
    <p>No new products found.</p>
  <% end %>

<% elsif params[:filter] == "recently_updated" %>
  <h2>Recently Updated Products</h2>
  <% if @recently_updated_products.any? %>
    <ul>
      <% @recently_updated_products.each do |product| %>
        <li><%= link_to product.name, product_path(product) %></li>
        <!-- You can add additional information here if needed -->
      <% end %>
    </ul>
    <%= paginate @recently_updated_products %>
  <% else %>
    <p>No recently updated products found.</p>
  <% end %>

<% end %>

<% if @products.any? && params[:filter] != "new" && params[:filter] != "recently_updated" %>
  <%= paginate @products %>
<% elsif !@products.any? %>
  <p>No products found.</p>
<% end %>

app/views/products/show.html.erb
<!-- Display details of a single product -->
<h1><%= @product.name %></h1>
<p>Description: <%= @product.description %></p>
<p>Category:  <%= link_to @product.category.name, category_path(@product.category) %> </p>
<p>Price: <%= @product.price %></p>
<!-- Add more details as needed -->

app/views/search/index.html.erb
<h1>Product Search</h1>

<%= form_with(url: search_index_path, method: :get) do |form| %>
  <div>
    <%= form.label :keyword, "Keyword:" %>
    <%= form.text_field :keyword, value: params[:keyword] %>
  </div>

  <div>
    <%= form.label :category_id, "Category:" %>
    <%= form.collection_select :category_id, @categories, :id, :name, { prompt: "All Categories" }, { onchange: "this.form.submit()" } %>
  </div>

  <div>
    <%= form.submit "Search" %>
  </div>
<% end %>

<% if @products.any? %>
  <h2>Search Results:</h2>
  <ul>
    <% @products.each do |product| %>
      <li> <%= link_to product.name, product_path(product) %></li>
    <% end %>
  </ul>
<% else %>
  <p>No products found.</p>
<% end %>